### ISSUE TITLE
extending a can Control with defaults properties is changing the super Class defaults

### ISSUE THREAD

**Issue by Mamuuut** [canjs/can-control#126]
If an Object is part of a Class defaults and this Class is extended with defaults having a different Object with the same property name. The super Class defaults Object properties will be overwritten.

Here is an example with CanJS v4:
https://codepen.io/Mamuuut/pen/oPGLgE

It was not the case in v3:
https://codepen.io/Mamuuut/pen/OoxXPq?editors=1111

And it still is in v5:
https://codepen.io/Mamuuut/pen/bKyryV

This seems related to the can Construct setup method:
```
	setup: function (base) {
		var defaults = canReflect.assignDeepMap({},base.defaults);
		this.defaults = canReflect.assignDeepMap(defaults,this.defaults);
	},
```
assignDeepMap does not create a deep copy of the base.defaults and then those are overwritten by this.defaults…

**Comment by justinbmeyer** [comment]
Can you try:

```
var defaults = canReflect.serialize(base.defaults);
this.defaults = canReflect.assignDeepMap(defaults,this.defaults);
```

Let me know if this works.  Thanks!

**Comment by Mamuuut** [comment]
It works:

https://codepen.io/Mamuuut/pen/MqEMaa

Thanks!

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-construct #65](https://github.com/canjs/can-construct/issues/65) via [**ZenHub**](https://www.zenhub.com/)
